In [4]:
# Import the required libraries and dependencies
import pandas as pd
import hvplot.pandas
from pathlib import Path
import numpy as np
import os

In [5]:
# Using the read_csv function and Path module, create a DataFrame 
# by importing the sfo_neighborhoods_census_data.csv file from the Resources folder
demo_estate_data_df = pd.read_csv(
    Path('./Resources/tableau_data_Filtered2.csv')
)

# Review the first and last five rows of the DataFrame
demo_estate_data_df

FileNotFoundError: [Errno 2] No such file or directory: 'Resources/tableau_data_Filtered2.csv'

In [ ]:
demo_estate_data_df.describe()

,Home Value,Inventory,median_listing_price,median_square_feet,RegionID,SizeRank
count,7.775910e+05,781524.000000,7.775910e+05,777591.000000,3960.000000,3960.000000
mean,3.375361e+05,111.820958,3.441598e+05,1820.806044,403758.941667,98.125000
std,4.201224e+05,815.710807,3.627208e+05,745.000656,56076.781886,127.481227
min,1.233700e+04,13.000000,2.000000e+02,0.000000,394304.000000,1.000000
25%,1.519680e+05,25.000000,1.680500e+05,1479.000000,394526.250000,30.750000
50%,2.358060e+05,48.000000,2.592775e+05,1803.500000,394814.500000,60.500000
75%,3.752120e+05,95.000000,3.950500e+05,2189.000000,395045.750000,90.250000
max,2.242418e+07,74902.000000,1.980005e+07,9012.000000,753924.000000,672.000000

In [ ]:
demo_estate_data_df.State.value_counts()

CA    38105
TX    34644
NY    32621
FL    27951
PA    23839
MI    20776
IL    19339
OH    16929
NJ    16239
NC    16030
VA    15870
GA    14810
WI    12907
MA    11943
TN    11894
MN    11567
MO    11135
AL    10190
IN    10164
WA    10071
CO     9711
MD     9030
AZ     8685
CT     7687
LA     7660
SC     7514
KY     7069
OR     7004
OK     6982
ME     6707
IA     6439
AR     6187
KS     5346
MS     4649
NH     4594
WV     4147
UT     4107
ID     3682
VT     3549
NV     3479
MT     3167
NM     3079
NE     3035
HI     1992
RI     1831
DE     1601
SD     1489
WY     1395
AK     1216
ND      969
DC      666
Name: State, dtype: int64

In [ ]:
tx_df = demo_estate_data_df.loc[demo_estate_data_df.State=="TX"]
tx_df

,zipCode,StateName,State,City,Metro,CountyName,Date,Home Value,Inventory,median_listing_price,median_square_feet,month_date_yyyymm,RegionID,SizeRank,postal_code
590682,75001,TX,TX,Addison,Dallas-Fort Worth-Arlington,Dallas County,10/31/2017,351009.0,25.0,370500.0,2069.0,201710.0,NaN,NaN,NaN
590683,75001,TX,TX,Addison,Dallas-Fort Worth-Arlington,Dallas County,11/30/2017,352627.0,27.0,375050.0,2129.0,201711.0,NaN,NaN,NaN
590684,75001,TX,TX,Addison,Dallas-Fort Worth-Arlington,Dallas County,12/31/2017,354777.0,25.0,379050.0,2002.0,201712.0,NaN,NaN,NaN
590685,75001,TX,TX,Addison,Dallas-Fort Worth-Arlington,Dallas County,1/31/2018,357192.0,19.0,377050.0,2014.0,201801.0,NaN,NaN,NaN
590686,75001,TX,TX,Addison,Dallas-Fort Worth-Arlington,Dallas County,2/28/2018,359760.0,20.0,370050.0,2053.5,201802.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
642314,79938,TX,TX,El Paso,El Paso,El Paso County,2/29/2020,161613.0,579.0,210000.0,1914.0,202002.0,NaN,NaN,NaN
642315,79938,TX,TX,El Paso,El Paso,El Paso County,3/31/2020,161684.0,550.0,211275.0,1952.0,202003.0,NaN,NaN,NaN
642316,79938,TX,TX,El Paso,El Paso,El Paso County,4/30/2020,161601.0,511.0,209500.0,1914.0,202004.0,NaN,NaN,NaN
642317,79938,TX,TX,El Paso,El Paso,El Paso County,5/31/2020,161363.0,398.0,214500.0,1954.0,202005.0,NaN,NaN,NaN
642318,79938,TX,TX,El Paso,El Paso,El Paso County,6/30/2020,161028.0,355.0,214750.0,1905.0,202006.0,NaN,NaN,NaN

In [ ]:
tx_city_df = demo_estate_data_df.loc[demo_estate_data_df.City=="Austin"]
#tx_df = demo_estate_data_df.loc[demo_estate_data_df.City=="Austin"]


tx_city_df

,zipCode,StateName,State,City,Metro,CountyName,Date,Home Value,Inventory,median_listing_price,median_square_feet,month_date_yyyymm,RegionID,SizeRank,postal_code
141892,16720,PA,PA,Austin,NaN,Potter County,10/31/2017,60024.0,17.0,175050.0,1523.0,201710,NaN,NaN,NaN
141893,16720,PA,PA,Austin,NaN,Potter County,11/30/2017,60310.0,17.0,175050.0,1523.0,201711,NaN,NaN,NaN
141894,16720,PA,PA,Austin,NaN,Potter County,12/31/2017,60592.0,17.0,175050.0,1523.0,201712,NaN,NaN,NaN
141895,16720,PA,PA,Austin,NaN,Potter County,1/31/2018,60880.0,14.0,194000.0,1523.0,201801,NaN,NaN,NaN
141896,16720,PA,PA,Austin,NaN,Potter County,2/28/2018,61316.0,13.0,162050.0,1523.0,201802,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
636790,78759,TX,TX,Austin,Austin-Round Rock,Travis County,2/29/2020,541216.0,15.0,489950.0,1730.0,202002.0,NaN,NaN,NaN
636791,78759,TX,TX,Austin,Austin-Round Rock,Travis County,3/31/2020,546128.0,20.0,489950.0,1850.5,202003.0,NaN,NaN,NaN
636792,78759,TX,TX,Austin,Austin-Round Rock,Travis County,4/30/2020,550979.0,35.0,474950.0,1902.0,202004.0,NaN,NaN,NaN
636793,78759,TX,TX,Austin,Austin-Round Rock,Travis County,5/31/2020,555528.0,37.0,524950.0,1929.0,202005.0,NaN,NaN,NaN
636794,78759,TX,TX,Austin,Austin-Round Rock,Travis County,6/30/2020,558182.0,34.0,484550.0,1960.0,202006.0,NaN,NaN,NaN

In [ ]:
austin_df = tx_df.loc[tx_df.City=="Austin"]
austin_df

,zipCode,StateName,State,City,Metro,CountyName,Date,Home Value,Inventory,median_listing_price,median_square_feet,month_date_yyyymm,RegionID,SizeRank,postal_code
633208,78617,TX,TX,Austin,Austin-Round Rock,Travis County,10/31/2017,191402.0,17.0,237050.0,1900.0,201710.0,NaN,NaN,NaN
633209,78617,TX,TX,Austin,Austin-Round Rock,Travis County,11/30/2017,192256.0,16.0,239198.0,2000.0,201711.0,NaN,NaN,NaN
633210,78617,TX,TX,Austin,Austin-Round Rock,Travis County,12/31/2017,192973.0,18.0,234196.0,1900.0,201712.0,NaN,NaN,NaN
633211,78617,TX,TX,Austin,Austin-Round Rock,Travis County,1/31/2018,194598.0,19.0,226911.5,2089.0,201801.0,NaN,NaN,NaN
633212,78617,TX,TX,Austin,Austin-Round Rock,Travis County,2/28/2018,195947.0,29.0,225096.0,2035.0,201802.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
636790,78759,TX,TX,Austin,Austin-Round Rock,Travis County,2/29/2020,541216.0,15.0,489950.0,1730.0,202002.0,NaN,NaN,NaN
636791,78759,TX,TX,Austin,Austin-Round Rock,Travis County,3/31/2020,546128.0,20.0,489950.0,1850.5,202003.0,NaN,NaN,NaN
636792,78759,TX,TX,Austin,Austin-Round Rock,Travis County,4/30/2020,550979.0,35.0,474950.0,1902.0,202004.0,NaN,NaN,NaN
636793,78759,TX,TX,Austin,Austin-Round Rock,Travis County,5/31/2020,555528.0,37.0,524950.0,1929.0,202005.0,NaN,NaN,NaN
636794,78759,TX,TX,Austin,Austin-Round Rock,Travis County,6/30/2020,558182.0,34.0,484550.0,1960.0,202006.0,NaN,NaN,NaN

In [6]:
starbucks_data_df= pd.read_csv(
    Path("../Resources/data/starbucks_data.csv")
)

In [7]:
display(starbucks_data_df.head())

,name,url,street_address,city,state,zip_code,country,phone_number_1,phone_number_2,fax_1,...,email_2,website,open_hours,latitude,longitude,facebook,twitter,instagram,pinterest,youtube
0,交易廣場,https://www.starbucks.com/store-locator/store/6,中環交易廣場3樓平台,香港,CN,NaN,US,21473739,NaN,NaN,...,NaN,NaN,"Wednesday : 6:30 AM to 8:30 PM, Thursday : 6:3...",22.283940,114.158190,NaN,NaN,NaN,NaN,NaN
1,德福廣場,https://www.starbucks.com/store-locator/store/8,九龍灣德福廣場一期A大堂G1A號,香港,CN,0,US,27541323,NaN,NaN,...,NaN,NaN,"Wednesday : 7:00 AM to 10:30 PM, Thursday : 7:...",22.322870,114.213440,NaN,NaN,NaN,NaN,NaN
2,荷李活廣場,https://www.starbucks.com/store-locator/store/1,九龍鑽石山荷里活廣場2樓298號鋪,香港,CN,NaN,US,29554570,NaN,NaN,...,NaN,NaN,"Wednesday : 8:30 AM to 10:30 PM, Thursday : 8:...",22.340700,114.201690,NaN,NaN,NaN,NaN,NaN
3,機鐵香港站,https://www.starbucks.com/store-locator/store/13,機鐵香港站HOK 3a & b 號,香港,CN,NaN,US,25375216,NaN,NaN,...,NaN,NaN,"Wednesday : 6:30 AM to 10:00 PM, Thursday : 6:...",22.284450,114.158460,NaN,NaN,NaN,NaN,NaN
4,太古廣場,https://www.starbucks.com/store-locator/store/17,"金鐘道太古廣場L1, 131號",香港,CN,0,US,29184762,NaN,NaN,...,NaN,NaN,"Wednesday : 7:00 AM to 9:30 PM, Thursday : 7:0...",22.277657,114.164619,NaN,NaN,NaN,NaN,NaN